### Server ###
server:
  port: 8888

### In-memory database ###
spring:
  datasource:
    schema: classpath*:db/hsqldb/schema.sql #为了项目启动有假数据可以查看,使用当前项目内置sql数据
    data: classpath*:db/hsqldb/data.sql #为了项目启动有假数据可以查看,使用当前项目内置sql数据
    ### Database for MySQL ###
#    url: jdbc:mysql://localhost:3306/oauth-oauth
#    username: oauth
#    password: qwer12345
#    driver-class-name: com.mysql.jdbc.Driver

### MyBatis ###
mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.waein.oauth.model

### Logging ### Log levels (TRACE, DEBUG, INFO, WARN, ERROR, FATAL, OFF)
logging:
  level: INFO
  # File output 上线需要配置服务器日志路径 /data/oauth/logs/oauth.log
  file: /Users/SeungRi/opt/logs/oauth.log